function MCmoduleStream = Pick_MCModuleStream(dFCstream, Modules, m)

% FUNCTION MCmoduleStream = Pick_MCModuleStream(dFCstream, Modules, m)
%
% This function takes as input: i) dFCstream is a dFCstream object generated by
% TS2dFCstream, in either stream or 3D formats (with N regions);
% ii) a vector Modules of size N^2 - N, giving
% the module label associated to a MC row (from a module structure extracted
% from a MC matrix generated by dFCstream2MC function);
% iii) the label m of the module to seek for, i.e. an integer between 1 and max(Modules)
% The output MCmoduleStream (always in vector format, independently from input
% format) is the stream of the dFC module #m extracted from the whole brain dFCstream

if (nargin < 3)
    disp('You should provide minimum as inputs a dFCstream, a Modules vector and a target module label m')
    return
end

if (ndims(dFCstream) == 3)
    FCstr = Matrix2Vec(dFCstream);
    nregions = size(dFCstream,1);
end

if (ndims(dFCstream) == 2)
    FCstr = dFCstream;
    nregions = (1+sqrt(1+8*size(dFCstream,1)))/2;
end

if (ndims(dFCstream) < 2)
    disp('Provide a valid size dFCstream (3D or stream objects)!')
    return
end

if (ndims(dFCstream) > 3)
    disp('Provide a valid size dFCstream (3D or stream objects)!')
    return
end


% Now FCstr is a stream 2D object
MCmoduleStream = Pick_SubgraphStream(FCstr, Which_StreamIndices_ThisMCmodule(Modules, m,'table'));


