function Substream = Pick_SubgraphStream(dFCstream, links)

% FUNCTION SubgraphStream = Pick_SubgraphStream(dFCstream, links)
% This function takes as input: i) dFCstream is a dFCstream object generated by
% TS2dFCstream, in either 2D or 3D formats;
% ii) list of links to include in the subgraph, in either vector ---from 1 to N(N-1)/2---
% or matrix ---pairs i, j, with i, j <= N--- formats.
% The output SubgraphStream (always in vector format, independently from input
% format) is the stream of the subgraph extracted from the whole brain dFCstream


invalidstream = 1;
if(size(dFCstream,3) > 1)
    TwoDdFCstream = Matrix2Vec(dFCstream);
    nregions = size(dFCstream,1);
    invalidstream = 0;
end
if(size(dFCstream,2) > 1)
    TwoDdFCstream = dFCstream;
    nregions = (1 + sqrt(1+8*size(dFCstream,1)))/2;
    invalidstream = 0;
end
if (invalidstream)
    disp('Provide a valid list of links (3D or stream objects) with at least one link in the link list!')
    return
end

nLinks = length(links);
if (nLinks == 0)
    disp('Provide a valid list of links (3D or stream objects) with at least one link in the link list!')
    return
end

invalidlinks = 1;
if (size(links,2) > 1)
    TwoDlinks = zeros(size(links,1),1);
    for l =1:size(links,1)
        TwoDlinks(l) = Which_StreamIndex_ThisLink(links(l,1), links(l,2), dFCstream);
    end
    invalidlinks = 0;
end
if (size(links,2) <= 1)
    TwoDlinks = links;
    invalidlinks = 0;
end
if (invalidlinks)
    disp('Provide a valid list of links (3D or stream objects)!')
    return
end

Substream = TwoDdFCstream(TwoDlinks, :);


